### ISSUE TITLE
halt remote execution

### ISSUE THREAD

**Issue by juliangruber** [jstrace/jstrace#22]
Once you start a script with remote execution it will run forever in the host process. 

To reproduce:
- start a server
- start remote tracing script
- ^C
- start remote tracing script
- see double output

**Comment by tj** [comment]
ah shit hahaha good call, if when we fix this intervals etc will be an issue

**Comment by juliangruber** [comment]
what about

``` js
exports.local = function(trace){
  // ...
  trace.on('cleanup', function(){
    // or "end"
  })
}
```

**Comment by juliangruber** [comment]
see https://github.com/jstrace/jstrace/pull/24, went with returning a function

**Comment by tj** [comment]
hmm yeah let's go with "end" or "close" maybe
