### ISSUE TITLE
how to send buffers

### ISSUE THREAD

**Issue by juliangruber** [jstrace/jstrace#28]
``` js
trace('request', { buf: buf })
```

will send `{buf:{"type":"buffer",data:[ ...` over the wire

**Comment by juliangruber** [comment]
i guess actorify should implement support for buffers in objects?

**Comment by tj** [comment]
yea we're kinda fucked that way, we'd have to use msgpack or similar but it's lame and slow. I think in 99% of these cases though it's better to use remote to send some reduced values to local for reporting, since most binary represents something huge like a file anyway

**Comment by tj** [comment]
closing for now but we could maybe come up with some sort of warning system, or remove them in the toJSON implementation so people don't accidentally ship massive blobs
