### ISSUE TITLE
Add faster trace() api

### ISSUE THREAD

**Issue by juliangruber** [jstrace/jstrace#32]
Creating objects for trace probes, like

``` js
trace('foo', { bar: 'baz' })
```

is by no means a noop when tracing is off.

This api would be way faster:

``` js
trace('foo', 'bar', 'baz')
trace('probe', 'keyA', objA, 'keyB', objB)
```

I created a jsperf case for this: http://jsperf.com/noop-object
I suggest adding this as an alternate api.

What do you think?

**Comment by tj** [comment]
meh it's still several million ops/s, doing any real work or IO at all will make that very negligible in comparison. It would be nice if we didn't force objects but I don't think it's a real problem. It could be if it's a tight render loop of some kind but if we had non-object support for those cases that would be cool, but even tracing those would probably halt a program pretty good haha

**Comment by juliangruber** [comment]
yeah true
